# Generated by Django 5.1.4 on 2025-01-29 15:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_podcast_delete_contact_alter_socialmedialink_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='socialmedialink',
            name='url',
            field=models.URLField(validators=[django.core.validators.URLValidator(schemes=['http', 'https', 'ftp'])]),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['-date'], name='event_date_index'),
        ),
    ]
