# Generated by Django 5.1.4 on 2025-02-26 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_genre_track_alter_event_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'Podcast'},
        ),
    ]
