# Generated by Django 5.1.4 on 2025-02-26 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_about_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'About'},
        ),
    ]
